// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:subtract': typeof import('~icons/carbon/subtract')['default']
    CarbonAdd: typeof import('~icons/carbon/add')['default']
    CarbonBin: typeof import('~icons/carbon/bin')['default']
    CarbonDustbin: typeof import('~icons/carbon/dustbin')['default']
    CarbonEdit: typeof import('~icons/carbon/edit')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonReply: typeof import('~icons/carbon/reply')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    CommentEditor: typeof import('./src/components/CommentEditor.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    CommentListItem: typeof import('./src/components/CommentListItem.vue')['default']
    ModalDeleteComment: typeof import('./src/components/ModalDeleteComment.vue')['default']
  }
}

export { }
